import type { Metadata } from "next";
import { PasskeyContext } from "@/lib/webauthn";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={"antialiased"}>
        <PasskeyContext useConditionalMediation={true}>
          {children}
        </PasskeyContext>
      </body>
    </html>
  );
}
